- name: update project on AAP system
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../secret.yml
  tasks:

    - name: update the projects ID 8
      uri:
        url: https://10.50.51.103/api/v2/projects/8/update/
        return_content: false
        user: "{{ vault_AAP_API_username }}"
        password: "{{ vault_AAP_API_password }}"
        method: POST
        validate_certs: no
        force_basic_auth: true
        status_code: [200, 202]
