- name: execution of a command on a Linux system
  hosts: "{{ serverName }}"
  gather_facts: no
  tasks:
    - name: execution of the command "{{ command_to_execute }}" on  the server named "{{ serverName }}"
      command: "{{ command_to_execute }}"
