- hosts: "{{ VMname }}"
  gather_facts: no
  tasks:
    - name: HTTPD service installation
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Enable and ON for HTTPD service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Add of the index.html file
      copy:
        src: index.html
        dest: /var/www/html/
        force: yes

    - name: Firewall configurationans name
      firewalld:
        service: http
        permanent: yes
        state: enabled
        zone: public
        immediate: yes