- name: test
  hosts: localhost
  connection: local
  gather_facts: no
  become: false
  vars:
    windows: "Windows"
  tasks:
    - name: Recuperation de toutes les informations de la VM nommee {{ nomVM }}
      community.vmware.vmware_guest_info:
        name: "{{ VM }}"
        datacenter: vSANDatacenter
        hostname: 10.50.51.5
        username: administrator@vsphere.local
        password: VMware1!
        validate_certs: False
      register: listeInfoVM

    - name: Affichage de l adresse IP de la VM nomme {{ nomVM }}
      debug:
        msg: "{{ listeInfoVM.instance.advanced_settings }}"

    - name: Est ce un Windows?
      debug:
        msg: Oui
      when: '"Windows" in listeInfoVM'
