- name: test
  hosts: vm-redhat-lg
  connection: ssh
  gather_facts: no
  vars:
    - aFaire: false
  tasks:
    - name: afficgae des facts
      stat:
        path: /etc/ansible-automation-platform/VERSION
      register: result

    - name: action a faire?
      debug:
        msg: "Resultat: {{ result.stat.exists }}"

    - name: action a faire?
      debug:
        msg: Action a faire car le fichier existe
      when: result.stat.exists is true and aFaire is true
