- name: Show value of a variable (Use for testing)
  hosts: localhost
  gather_facts: no
  vars:
    var_to_show: "Result is OK. Varibale is shown!"
  tasks:
    - name: Show value of a variable (Use for testing)
      ansible.builtin.debug:
        msg: "{{ var_to_show }}"