- name: test
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vault_file.yml
  tasks:
    - name: test
      become: no
      win_domain_computer:
        name: vm-redhat-c.bsclab.local
        state: absent
      delegate_to: srvad1.bsclab.local
