- name: test
  hosts: vm-redhat-aap
  gather_facts: no
  vars:
    - var: automation-controller.service2
  tasks:
  - name: Analyse of the target to receive the service facts
    service_facts:

  - name: affichage de la variable
    debug:
      msg: "La variable est  {{ var }} !"

  - name: AAP service named "{{ vmware_deploy_service_AAP }}" is not found, it is a Ansible machine
    debug:
      msg: "Dedans!"
    when: var not in ansible_facts.services
