---
- name: Deploiement de la machine  "{{ nomVM }}"
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vault_file.yml
  
  roles:
    - ../Roles/vmware_deploy_and_configure
