---
#Deployment and configure of a new VM Red Hat
- name: Deployment of "{{ nomVM }}"
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    #Vault file is needed because we use password and sensibled data stored in this document
    - ../vault_file.yml
  
  roles:
    #Role used to deply VM on VCenter target and configure Ansible connexion (SSH Key, add user...)
    - ../Roles/vmware_deploy_RHEL_and_configure_Ansible_connection

#Add the new VM in Red Hat Insight system 
- name: Add of the new VM named "{{ nomVM }}" in the Red Hat Insight system
  hosts: "{{ nomVM }}"
  connection: ssh
  gather_facts: no
  vars_files:
    #Vault file is needed because we use password and sensibled data stored in this document
    - ../vault_file.yml
  
  roles:
    #Role used to add the new VM in Red Hat Insight 
    - ../../.ansible/roles/RedHatInsights.insights-client
  vars:
    #This variables are needed to add the new VM in Red Hat Insight (Data stored in the Vault file)
    redhat_portal_username: "{{ RHN_compte }}"
    redhat_portal_password: "{{ RHN_password }}"