#Management of the need variables
- name: Management of the need variables
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Check the "VMname" variable
      fail:
        msg:
          - "Variable named VMname is not defined and is mandatory"
          - "Variable named VMname will be the name of the new VM deployed using this Playbook"
      when: VMname is not defined

#Deployment and configure of a new VM Red Hat
- name: Deployment of "{{ VMname }}"
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    #Vault file is needed because we use password and sensibled data stored in this document
    - ../secret.yml
  
  roles:
    #Role used to deply VM on VCenter target and configure Ansible connexion (SSH Key, add user...)
    - ../Roles/vmware-RHEL_deploy
