- name: creation of a new user in Microsoft domain
  hosts: "{{ domain_controller }}"
  become: no
  gather_facts: no
  vars_files:
    - ../vault_file.yml
  tasks:
    - name: creation of the user named "{{ user_to_create }}" in the domain named "{{ microsoft_domain }}"
      win_domain_user:
        name: "{{ user_to_create }}"
        firstname: created_by_AAP
        surname: created_by_AAP
        password: azerty@12345
        description: user created by AAP system
        enabled: yes
        groups: Domain Admins
        state: present
        password_never_expires: yes
        user_cannot_change_password: no
        attributes:
          userWorkstations: srvad1
          manager: AAP
