- name: Creation of a user named "{{ username }}" in the Microsoft domain and AD "{{ vault_AD_computer_name }}"
  hosts: "{{ vault_AD_DomainController_Name }}"
  become: no
  gather_facts: no
  vars_files:
    - ../secret.yml
  tasks:

    - name: Test if the username is set
      when: username is not defined
      ansible.builtin.fail:
        msg:
          Problem: The username data is not set. It is mandatory.

    - name: Test if the password of the user is set
      when: username_password is not defined
      ansible.builtin.fail:
        msg:
          Problem: The user password data is not set. It is mandatory.

    - name: Creation of the user named "{{ username }}"
      win_domain_user:
        name: "{{ username }}"
        sam_account_name: "{{ username }}"
        firstname: "{{ firstname | default('firstname') }}"
        surname: "{{ surname | default('surname') }}"
        password: "{{ username_password }}"
        description: "{{ description | default('User created by AAP system') }}"
        enabled: yes
        groups: users
        state: present
        password_never_expires: yes
        user_cannot_change_password: yes
        update_password: when_changed
        email: none@none.com
        display_name: "{{ username }}"
        attributes:
          telephoneNumber: 2626
          initials: AAP