- name: Creation of a user named "{{ username }}" in the Microsoft domain and AD "{{ vault_AD_computer_name }}"
  hosts: "{{ vault_AD_DomainController_Name }}"
  become: no
  gather_facts: no
  vars_files:
    - ../secret.yml
  tasks:

    - name: Test the needed variable which has to be set
      when: username is not defined
      ansible.builtin.fail:
        msg:
          Problem: needed variable name username and vault_AD_DomainController_Name are not set

    - name: Creation of the user named tg "{{ username }}"
      win_domain_user:
        name: "{{ username }}"
        firstname: created_by_AAP
        surname: created_by_AAP
        password: "{{ username_password }}"
        description: user created by AAP system
        enabled: yes
        #groups: Domain Admins
        state: present
        password_never_expires: yes
        user_cannot_change_password: yes
