- name: Suppression de la VM "{{ nomVM }}"
  vmware_guest:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    validate_certs: False
    name: "{{ nomVM }}"
    datacenter: "{{ vmware_datacenter }}"
    state: absent
    force: yes
