- name: Enregistrement de la machine "{{ nomVM }}" sur le RHN, via le compte "{{ RHN_compte }}" avec auto attach
  connection: ssh
  community.general.redhat_subscription:
    state: present
    username: "{{ RHN_compte }}"
    password: "{{ RHN_password }}"
    auto_attach: true
  delegate_to: "{{ item }}"
  with_items: "{{ nomVM }}"
  when: nomVM.find("redhat") != -1
  ignore_errors: true

- name: Enregistrement de la machine sur Red Hat Insight
  connection: ssh
  roles:
        - /root/.ansible/roles/RedHatInsights.insights-client
  vars:
    redhat_portal_username: "{{ RHN_compte }}"
    redhat_portal_password: "{{ RHN_password }}"
  delegate_to: "{{ item }}"
  with_items: "{{ nomVM }}"
  when: nomVM.find("redhat") != -1
  ignore_errors: true
