#Taches a faire pour deployer des VMs et les configurer
- include_tasks: 1-deploy_VM.yml
- include_tasks: 2-get_ipv4_address.yml
- include_tasks: 3-add_host_in_inventory.yml
  #- include_tasks: 4-set_config_to_OS.yml
  #vars:
  #- ipVM: "{{ listeInfoVM.instance.ipv4 }}"
  #- pwdHashe: "{{ ansible_user_password | password_hash('sha512') }}"
  #- include_tasks: 5-hostname_change_and_reboot.yml
  # vars:
  #- ipVM: "{{ listeInfoVM.instance.ipv4 }}"


      #- include_tasks: hostname_change_and_reboot.yml
      #  vars:
      #- ipVM: "{{ listeInfoVM.instance.ipv4 }}"
      #- include_tasks: add_host_in_website.yml
      #  vars:
      #- ipVM: "{{ listeInfoVM.instance.ipv4 }}"
      #- include_tasks: system_update.yml
      #vars:
      #- ipVM: "{{ listeInfoVM.instance.ipv4 }}"
