- name: Parameters for the new VM to deploy are listed below
  debug:
    msg:
      - "------------------------------------------------------------------------ "
      - "New VM configuration:"
      - "->Number of CPUs: {{ vmware_deploy_hardware_cpus }}." 
      - "->Number of RAM memory: {{ vmware_deploy_hardware_memory }}mb."
      - "->Hot add for CPUs: {{ vmware_deploy_hardware_cpus_hot_add }}."
      - "->Hot add for memory: {{ vmware_deploy_hardware_memory_hot_add }}."
      - "->Patching of the VM: {{ vmware_deploy_update_state }}."
      - "->Patching to do: {{ vmware_deploy_patching_to_do }}."
      - "------------------------------------------------------------------------ "
      - "Information:"
      - "->Deployment will wait the VM to response before continue to other step."
      - "------------------------------------------------------------------------" 

- name: Deployment of the new VM named "{{ VMname }}" on VCenter platform "{{ vmware_deploy_vcenter_hotname }}"
  community.vmware.vmware_guest:
    hostname: "{{ vmware_deploy_vcenter_hotname }}"
    username: "{{ vmware_deploy_vcenter_username }}"
    password: "{{ vmware_deploy_vcenter_password }}"
    validate_certs: False
    name: "{{ VMname }}"
    template: "{{ vmware_deploy_template }}"
    datacenter: "{{ vmware_deploy_vcenter_datacenter }}"
    folder: "{{ vmware_deploy_folder }}"
    state: poweredon
    wait_for_ip_address: yes
     disk:
    - size_gb: 100
      type: thin
      #datastore: g73_datastore
    hardware:
      memory_mb: "{{ vmware_deploy_hardware_memory }}"
      num_cpus: "{{ vmware_deploy_hardware_cpus }}"
      hotadd_memory: "{{ vmware_deploy_hardware_memory_hot_add }}"
      hotadd_cpu: "{{ vmware_deploy_hardware_cpus_hot_add }}"
