- name: Add the new VM named "{{ VMname }}" in the memory inventory file
  ansible.builtin.add_host:
      name: "{{ VMname }}"
      ansible_connection: "ssh"
      ansible_user: "{{ vault_ansible_user_for_linux }}"
      ansible_ssh_pass: "{{ vault_ansible_user_for_linux_password }}"