- name: Suppression de la VM "{{ nomVM }}"
  vmware_guest:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    validate_certs: False
    name: "{{ nomVM }}"
    template: "{{ vmware_RedHat_template }}"
    datacenter: "{{ vmware_datacenter }}"
    folder: "{{ vmware_RedHat_folder }}"
    state: absent
    wait_for_ip_address: yes
    resource_pool: Red Hat
    force: yes
