- name: execution of a command on a Windows system
  hosts: "{{ serverName }}"
  become: no
  gather_facts: no
  vars_files:
    - ../vault_file.yml
  tasks:
    - name: execution of the command "{{ command_to_execute }}" on  the server named "{{ serverName }}"
      win_command: "{{ command_to_execute }}"
      register: command_result

    - name: Result show
      debug:
        msg: command_result.stdout