- name: Copie du fichier sshd_config sur le cible
  copy:
    src: ../file/sshd_config
    dest: /etc/ssh/
    owner: root
    group: root
    mode: 0644

#- name: Copie du fichier banner sur le cible
  #copy:
    #src: ../file/banner
    #dest: /etc/
    #owner: root
    #group: root
    #mode: 0644

- name: Creation de la banniere sur la cible via le template Jinja
  template:
    src: ../templates/banner.j2
    dest: /etc/banner
  notify:
    sshd_service_restart