- name: Deployment of the new VM named "{{ VMname }}"
  hosts: localhost
  gather_facts: no
  become: no
  vars_files:
    - ../../Vault/secret.yml
  vars:
    vcenter: "{{ vault_vmware_hostname }}"
    username: "{{ vault_vmware_username }}"
    password: "{{ vault_vmware_password }}"
    cert: False

  tasks:

    - name: create the VM
      vmware.vmware_rest.vcenter_vm:
        vcenter_hostname: "{{ vcenter }}"
        vcenter_username: "{{ username }}"
        vcenter_password: "{{ password }}"
        vcenter_validate_certs: "{{ cert }}"
        name: "{{ VMname }}"
        guest_OS: RHEL_9_64
        placement:
          folder: "group-v52554"
          datacenter: "DCA"
          datastore: "datastore-12316"
          cluster: "domain-c11"
        state: present
        power_on: true