- name: test
  hosts: "{{ VM }}"
  become: no
  gather_facts: no
  vars_files:
    - ../../vault/secret.yml

  tasks:

    - name: execute the "hostname" command on windows target
      ansible.windows.win_command: hostname