- hosts: "{{ VM }}"
  gather_facts: no
  vars_files:
    - ../../Vault/secret.yml
  
  tasks:

    - name: Recuperation du nom de fichier de l interface reseau
      register: fichier_reseau_a_modifier
      ansible.builtin.find:
        paths: /etc/NetworkManager/system-connections
        patterns: 'ens*.nmconnection'

    - name: Affichage des donnees liees a la recup du fichier reseau
      ansible.builtin.debug:
        var: fichier_reseau_a_modifier

    - name: Affichage 2
      ansible.builtin.debug:
        msg: "{{ fichier_reseau_a_modifier._ansible_verbose_always }}"