- name: Deploiement de la VM nommee "{{ VMname }}"
  hosts: localhost
  gather_facts: no
  become: no
  vars_files:
    - ../../Vault/secret.yml

  tasks:

    - name: Get all portgroups in dvswitch vDS
      community.vmware.vmware_dvs_portgroup_find:
        hostname: "{{ vault_vmware_hostname }}"
        username: "{{ vault_vmware_username }}"
        password: "{{ vault_vmware_password }}"
        validate_certs: no
        dvswitch: 'tgrevellec'
      delegate_to: localhost
  
    - name: Creation de la VM
      community.vmware.vmware_guest:
        hostname: "{{ vault_vmware_hostname }}"
        username: "{{ vault_vmware_username }}"
        password: "{{ vault_vmware_password }}"
        datacenter: "DCA"
        validate_certs: no
        folder: "/DCA/vm/Environnement/tgrevellec"
        name: "{{ VMname }}"
        state: poweredon
        template: tg-template-rhel_9
        customization:
          domain: thibgrev.fr
          domainadmin: administrateur@THIBGREV.FR
          domainadminpassword: "azerty@12345"
          hostname: "{{ VMname }}"
          joindomain: thibgrev.fr
        hardware:
          memory_mb: 2048
          num_cpus: 2
          num_cpu_cores_per_socket: 2
          hotadd_cpu: true
          hotremove_cpu: true
          hotadd_memory: false
        networks:
        - name: DCA\tgrevellec
          #device_type: vmxnet3
          connected: true
        wait_for_ip_address: true