- name: Suppression de la VM nommee "{{ VMname }}"
  hosts: localhost
  gather_facts: no
  become: no
  vars:
    VMname: "tg-00000"
  vars_files:
    - ../../Vault/secret.yml

  tasks:

    - name: Suppression de la VM "{{ VMname }}"
      community.vmware.vmware_guest:
        hostname: "{{ vault_vmware_hostname }}"
        username: "{{ vault_vmware_username }}"
        password: "{{ vault_vmware_password }}"
        datacenter: "DCA"
        validate_certs: no
        folder: "{{ vault_vmware_folder }}"
        name: "{{ VMname }}"
        state: absent
        force: true

    - name: Affichage du resultat
      ansible.builtin.debug:
        msg: "La VM nommee {{ VMname }} a ete supprimee avec succe."