- name: Copie du fichier sshd_config sur le cible
  copy:
    src: ../file/sshd_config
    dest: /etc/ssh/
    owner: root
    group: root
    mode: 0644
  notify:
    sshd_service_restart
  when: 
    "{{ ansible_host }}" is not "tg-centreon"