- name: Creation de la banniere sur la cible via le template Jinja
  template:
    src: ../templates/banner.j2
    dest: /etc/banner
  notify:
    sshd_service_restart
  when: 
    ansible_host is not "tg-centreon"