- name: Enregistrement de la machine "{{ nomVM }}" sur le RHN, via le compte "{{ RHN_compte }}" avec auto attach
  connection: ssh
  community.general.redhat_subscription:
    state: present
    username: "{{ RHN_compte }}"
    password: "{{ RHN_password }}"
    auto_attach: true
  delegate_to: "{{ item }}"
  with_items: "{{ nomVM }}"
  when: nomVM.find("redhat") != -1