#Taches a faire pour deployer des VMs et les configurer
- include_tasks: deploy_VM.yml
- include_tasks: get_ipv4_address.yml
- include_tasks: add_host_in_DNS.yml
  vars:
    - ipVM: "{{ listeInfoVM.instance.ipv4 }}"
- include_tasks: add_host_in_inventory.yml
- include_tasks: set_config_to_OS.yml
  #- include_tasks: hostname_change_and_reboot.yml
  #- include_tasks: add_host_in_website.yml
  #- include_tasks: system_update.yml
