
# Configuration si l OS est un RHEL

- name: Creation de l utilisateur {{ userAnsible }} pour que Ansible puisse se connecter, sur {{ nomVM }}
  shell: command sshpass -p {{ root_password }} ssh -o StrictHostKeyChecking=no {{ compte }}@{{ nomVM }} 'useradd {{ userAnsible }}'
  register: sortie_creation
  #ignore_errors: yes
  when: nomVM.find("redhat") != -1

- name: Modification du password de {{ userAnsible }} sur {{ nomVM }}
  shell: command sshpass -p {{ root_password }} ssh -o StrictHostKeyChecking=no {{ compte }}@{{ nomVM }} 'echo {{ ansible_user_password }} | passwd --stdin {{ userAnsible }}'
    #register: sortie_modification_password
  when: nomVM.find("redhat") != -1

- name: Ajout de la cle publique {{ clePublique_AnsibleUser }} de {{ userAnsible }} sur la machine {{ nomVM }}
  shell: command sshpass -p {{ root_password }} ssh-copy-id -i {{ clePublique_AnsibleUser }} {{ userAnsible }}@{{ nomVM }}
  when: nomVM.find("redhat") != -1

- name: Ajout de la cle publique {{ clePublique_Root }} sur la machine {{ nomVM }} pour root
  shell: command sshpass -p {{ root_password }} ssh-copy-id -i {{ clePublique_Root }} root@{{ nomVM }}
  when: nomVM.find("redhat") != -1

- name: Ajout du compte {{ userAnsible }} dans le group WHEEL
  shell: command sshpass -p {{ root_password }} ssh -o StrictHostKeyChecking=no {{ compte }}@{{ nomVM }} 'usermod -aG wheel {{ userAnsible }}'
  when: nomVM.find("redhat") != -1

- name: Import du fichier de conf "{{ fichierSudoers }}" sur la machine cible
  shell: command sshpass -p "{{ root_password }}" rsync "{{ fichierSudoers }}" {{ compte }}@{{ nomVM }}:/etc/sudoers.d/
  when: nomVM.find("redhat") != -1

# Configuration si l OS est un Windows


