---
- name: Creation d'une VM a partir d'un template sur VMWare
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Deploiement de la VM
    vmware_guest:
      hostname: 10.50.51.5
      username: administrator@vsphere.local
      password: VMware1!
      validate_certs: False
      name: "{{ nomVM }}"
      template: RHEL9
      datacenter: vSAN Datacenter
      folder: Red Hat
      state: poweredon
      wait_for_ip_address: yes
      resource_pool: Red Hat

- name: Ajout de la mahine "{{ nomVM }}" dans l inventaire d Ansible
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ../Roles/inventory_add_host
    - ../Roles/vmware_get_ipv4_of_VM
    - ../Roles/dns_add_host
    - ../Roles/rhel_set_ansible_connexion_config
  vars:
    ipVM: "{{ listeInfoVM.instance.ipv4 }}"

- name: Changement du hostname de la nouvelle machine deployee
  hosts: "{{ nomVM }}"
  gather_facts: no
  tasks:
    - name: Changement du hostname
      hostname:
        name: "{{ nomVM }}"

