- name: Get the IP address of the new VM named "{{ nomVM }}"
  community.vmware.vmware_guest_info:
    name: "{{ nomVM }}"
    datacenter: "{{ vmware_datacenter }}"
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    validate_certs: False
  register: listeInfoVM

- name: Print of the IP address of the new VM named "{{ nomVM }}"
  debug:
    msg: "IP address of {{ nomVM }} est {{ ipVM }}."
  vars:
    ipVM: "{{ listeInfoVM.instance.ipv4 }}"
