- name: Add the new VM named "{{ nomVM }}" in the Ansible inventory file "{{ vmware_deploy_ansible_inventory_file }}", in the group named "{{ vmware_deploy_group_for_VM }}"
  lineinfile:
      line: "{{ nomVM }}"
      path: "{{ vmware_deploy_ansible_inventory_file }}"
      state: present
      insertafter: "{{ vmware_deploy_group_for_VM }}"

- name: Add the new VM named "{{ nomVM }}" in the memory inventory file
  add_host:
      name: "{{ nomVM }}"
      group: "{{ vmware_deploy_group_for_VM }}"
