- name: Update of the new VM named "{{ nomVM }}" using command-line "yum update *"
  #SSH connexion use because the operation will ba set on the target
  connection: ssh
  yum:
    state: latest
    name: "*"
  #The operation has to be done on the target
  delegate_to: "{{ nomVM }}"