- name: Creation de l utilisateur {{ userAnsible }} pour que Ansible puisse se connecter, sur {{ nomVM }}
  shell: command sshpass -p {{ root_password }} ssh -o StrictHostKeyChecking=no {{ compte }}@{{ nomVM }} 'useradd {{ userAnsible }}'
  register: sortie_creation
  #ignore_errors: yes

- name: Modification du password de {{ userAnsible }} sur {{ nomVM }}
  shell: command sshpass -p {{ root_password }} ssh -o StrictHostKeyChecking=no {{ compte }}@{{ nomVM }} 'echo {{ ansible_user_password }} | passwd --stdin {{ userAnsible }}'
    #register: sortie_modification_password

- name: Ajout de la cle publique {{ clePublique }} de {{ userAnsible }} sur la machine {{ nomVM }}
  shell: command sshpass -p {{ root_password }} ssh-copy-id -i {{ clePublique_AnsibleUser }} {{ userAnsible }}@{{ nomVM }}

- name: Ajout de la cle publique {{ clePublique }} sur la machine {{ nomVM }} pour root 
  shell: command sshpass -p {{ root_password }} ssh-copy-id -i {{ clePublique_Root }} root@{{ nomVM }}

- name: Ajout du compte {{ userAnsible }} dans le group WHEEL
  shell: command sshpass -p {{ root_password }} ssh -o StrictHostKeyChecking=no {{ compte }}@{{ nomVM }} 'usermod -aG wheel {{ userAnsible }}'

- name: Import du fichier de conf sudoers sur la machine cible
  shell: command sshpass -p "{{ root_password }}" rsync ../Roles/rhel_set_ansible_connexion_config/files/99-Ansible_user  {{ compte }}@{{ nomVM }}:/etc/sudoers.d/
