- name: Add host to Centreon
  uri:
    url: "{{ centreon_api_url }}"
    method: GET
    headers:
      Content-Type: "application/json"
      Centreon-Token: "{{ centreon_api_token }}"
    body_format: json
    body:
      name: "{{ host_name }}"
      address: "{{ host_name }}"
    body:
      action: "add"
      host_name: "{{ host_name }}"
      host_address: "{{ host_name }}"
  register: add_host_result

- debug:
    var: add_host_result