#Deploymnent on VMWare platform
vmware_deploy_vcenter_hotname: "{{ vault_vmware_hostname }}"
vmware_deploy_vcenter_username: "{{ vault_vmware_username }}"
vmware_deploy_vcenter_password: "{{ vault_vmware_password }}"
vmware_deploy_vcenter_datacenter: "{{ vault_vmware_datacenter }}"
vmware_deploy_template: "template_name"
vmware_deploy_folder: "{{ vault_vmware_folder }}"
vmware_deploy_hardware_memory: 4096
vmware_deploy_hardware_cpus: 4
vmware_deploy_hardware_memory_hot_add: true
vmware_deploy_hardware_cpus_hot_add: true
vmware_deploy_hardware_disk_size: 100
vmware_deploy_hardware_disk_type: "thin"
vmware_deploy_hardware_datastore_name: "GOLD-SF-ISCSI-87"
#Add in DNS server
vmware_deploy_type: A
vmware_deploy_zone: "{{ vault_domain_name }}"
vmware_deploy_domain_controller: "{{ vault_domain_controller }}"
#Add host in inventory
vault_ansible_user_for_linux: "{{ vault_ansible_user_for_linux }}"
vault_ansible_user_for_linux_password: "{{ vault_ansible_user_for_linux_password }}"
#Variables for adding the new VM in Red Hat account
vmware_deploy_RH_account: "{{ vault_redhat_RHN_account }}"
vmware_deploy_RH_password: "{{ vault_redhat_RHN_password }}"
#Variables for the update of the new VM
vmware_deploy_update_state: latest
vmware_deploy_patching_to_do: "yes"
#Variables for adding the new VM in the Microsoft Domain
vmware_deploy_domain: "{{ vault_domain_name }}"
vmware_deploy_domain_join_AD_user: "{{ vault_ansible_user_for_windows }}"
vmware_deploy_domain_join_AD_user_password: "{{ vault_ansible_user_for_windows_password }}"
vmware_deploy_computer_Linux_OU: "OU=Linux,OU=TG-Ordinateurs,DC=thibgrev,DC=fr"